name: Stylist
favicon: null
layout_spectrum: 0.6355677235405892
typography_spectrum: 0.16488369298167527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8028868224937469
  lightness: 0.8221787665970623
  saturation: 0.01940898015163839
  rhythmicContrast: 0.8986013485118747
purpose: []
